/**
 * POST /api/pdf
 *
 * Accepts { html: string, filename: string } and returns a real, text-based
 * A4 PDF generated by headless Chromium via Puppeteer.
 *
 * The Chromium binary is NOT bundled (that would exceed Vercel's 50 MB limit).
 * Instead, @sparticuz/chromium-min downloads the pack tarball from GitHub
 * Releases on first use and caches it in /tmp for subsequent warm invocations.
 */

import type { VercelRequest, VercelResponse } from '@vercel/node';
import chromium from '@sparticuz/chromium-min';
import puppeteer from 'puppeteer-core';

// Increase body parser limit — the HTML payload includes all app CSS + resume
// clone and can reach 2–4 MB.
export const config = {
  api: { bodyParser: { sizeLimit: '8mb' } },
};

// Pre-built Chromium pack for x64 Linux (Lambda / Vercel).
// Update the version here when bumping @sparticuz/chromium-min.
const CHROMIUM_PACK =
  'https://github.com/Sparticuz/chromium/releases/download/v148.0.0/chromium-v148.0.0-pack.x64.tar';

export default async function handler(req: VercelRequest, res: VercelResponse) {
  if (req.method !== 'POST') {
    return res.status(405).json({ error: 'Method not allowed' });
  }

  const { html, filename } = req.body as { html?: string; filename?: string };
  if (!html || typeof html !== 'string') {
    return res.status(400).json({ error: 'html is required' });
  }

  // Sanitise the suggested download name — strip chars that are invalid in
  // Content-Disposition filenames across all platforms.
  const safeName = ((filename ?? 'resume') + '.pdf')
    .replace(/[^\w.\-]/g, '_')
    .replace(/_+/g, '_');

  let browser;
  try {
    const executablePath = await chromium.executablePath(CHROMIUM_PACK);

    browser = await puppeteer.launch({
      args: chromium.args,
      executablePath,
      headless: true,
    });

    const page = await browser.newPage();
    page.setDefaultTimeout(20_000);

    // 'load' waits for the Google Fonts stylesheet to arrive.
    // We then explicitly wait for document.fonts.ready so the font files
    // (woff2) are fetched and decoded before the PDF is captured.
    await page.setContent(html, { waitUntil: 'load', timeout: 15_000 });
    await page.evaluate(() =>
      Promise.race([
        document.fonts.ready,
        new Promise<void>((r) => setTimeout(r, 5_000)),
      ])
    );

    const pdf = await page.pdf({
      format: 'A4',
      margin: { top: '0', right: '0', bottom: '0', left: '0' },
      printBackground: true,
    });

    res.setHeader('Content-Type', 'application/pdf');
    res.setHeader('Content-Disposition', `attachment; filename="${safeName}"`);
    res.setHeader('Cache-Control', 'no-store');
    return res.send(Buffer.from(pdf));
  } catch (err) {
    console.error('[pdf] generation failed:', err);
    return res.status(500).json({ error: 'PDF generation failed. Please try again.' });
  } finally {
    await browser?.close();
  }
}
